### ISSUE TITLE
Configured vlan -1 is not defined on this switch

### ISSUE THREAD

**Issue by Keksstar** [openl2m/openl2m#9]
Hi there!

Added two switches: One Cisco SG350-10SFP and one Planet WGS-4215-8T2S
On both are VLANs 1,2,3 configured, but I can´t change any VLANs on these...

Ironically I don´t have an "Warning" tab on these.
![grafik](https://github.com/user-attachments/assets/0e975453-7574-4a99-a59b-15dedb37c3d4)

The switches are in an switch group, which has an VLAN group, which has VLANs:
![grafik](https://github.com/user-attachments/assets/b783d12c-1bf9-41c2-be37-0bbdab5e1a64)

**Comment by johanreinalda** [comment]
This is basically the same at #8, closing
